backend:
  name: github
  repo: jacomago/jacomago.github.io # Path to your GitHub repository
  # optional, defaults to master
  # branch: main
  site_domain: e38bdf92-f083-4395-966d-cbb172a0c4e5
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/archive" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "tags", name: "taxonomies.tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }